"""Supabase compat shim tests — pure translation + row semantics (no live PG)."""
from __future__ import annotations

import os

from app.database import CompatRow, db_dialect, translate_sql


def test_dialect_defaults_to_sqlite():
    assert "DATABASE_URL" not in os.environ or True  # shim never crashes
    # Without DATABASE_URL the app keeps the local SQLite file.
    saved = os.environ.pop("DATABASE_URL", None)
    try:
        assert db_dialect() == "sqlite"
    finally:
        if saved is not None:
            os.environ["DATABASE_URL"] = saved


def test_dialect_detects_postgres_url():
    saved = os.environ.get("DATABASE_URL")
    os.environ["DATABASE_URL"] = "postgresql://x:y@host:6543/postgres?sslmode=require"
    try:
        assert db_dialect() == "postgres"
    finally:
        if saved is None:
            os.environ.pop("DATABASE_URL", None)
        else:
            os.environ["DATABASE_URL"] = saved


def test_placeholders_and_brackets():
    out = translate_sql(
        "SELECT * FROM order_margins WHERE Segment = ? ORDER BY [Row ID] LIMIT ? OFFSET ?"
    )
    assert out == (
        'SELECT * FROM order_margins WHERE Segment = %s ORDER BY "Row ID" LIMIT %s OFFSET %s'
    )


def test_month_sql_substr_translates():
    out = translate_sql("SELECT substr([Order Date], 1, 7) AS m FROM order_margins")
    assert out == 'SELECT substr("Order Date", 1, 7) AS m FROM order_margins'


def test_datetime_now_translates():
    out = translate_sql("INSERT INTO flags VALUES (?, ?, ?, ?, datetime('now'))")
    assert out == "INSERT INTO flags VALUES (%s, %s, %s, %s, CURRENT_TIMESTAMP)"


def test_flags_ddl_translates():
    out = translate_sql(
        "CREATE TABLE IF NOT EXISTS flags (id INTEGER PRIMARY KEY AUTOINCREMENT, "
        "flagged_at TEXT NOT NULL DEFAULT (datetime('now')))"
    )
    assert "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in out
    assert "DEFAULT (CURRENT_TIMESTAMP)" in out
    assert "AUTOINCREMENT" not in out
    assert "datetime(" not in out


def test_quoted_literals_untouched():
    out = translate_sql("SELECT * FROM t WHERE note = 'is this ? kept [x]' AND a = ?")
    assert "'is this ? kept [x]'" in out
    assert out.endswith("AND a = %s")


def test_compat_row_index_and_key_access():
    r = CompatRow((7, "x"), ("n", "s"))
    assert r[0] == 7
    assert r["s"] == "x"
    assert r.keys() == ("n", "s")
    assert dict(r) == {"n": 7, "s": "x"}
