"""Database connection helper.

SQLite (file data/marginmap.db) is the dev default. Set DATABASE_URL to point
at Supabase Postgres and the same queries run unchanged through a thin compat
shim (assumption A9: same schema shapes, standard SQL).

Supabase URL to use (Dashboard -> Settings -> Database -> Connection string):
the **Session Pooler** builds a `postgresql://postgres.<ref>:<pwd>@
aws-0-<region>.pooler.supabase.com:6543/postgres?sslmode=require`-style URL
(port 6543). Session mode speaks plain Postgres wire protocol, so DDL,
parameterized LIMIT/OFFSET, and per-request connections all work with no
driver quirks. (The Transaction pooler would need prepared-statement
workarounds — only switch if you exhaust pooled connections.)

The shim translates the three SQLite-isms used by this codebase:
  1. `?` placeholders            -> `%s` (quote-aware: `?` inside '...' kept)
  2. `[bracket identifiers]`      -> `"quoted identifiers"` (outside literals)
  3. `datetime('now')`            -> `CURRENT_TIMESTAMP` (raw pre-pass)
  4. `INTEGER PRIMARY KEY AUTOINCREMENT` -> `INTEGER GENERATED BY DEFAULT
     AS IDENTITY PRIMARY KEY`
Everything else (substr(), CASE, LIMIT/OFFSET params, double-quoted names)
is valid Postgres already. Rows come back as CompatRow, which supports both
`row[0]` (scalars via fetchone()[0]) and `row["col"]` / `dict(row)`, exactly
like sqlite3.Row — so no query call-site changes anywhere.
"""
from __future__ import annotations

import os
import re
import sqlite3
from pathlib import Path
from typing import Any, Sequence

# backend/app/database.py -> project root = parents[2]
ROOT = Path(__file__).resolve().parents[2]
DB_PATH = ROOT / "data" / "marginmap.db"


def db_dialect() -> str:
    """'postgres' when DATABASE_URL is set (Supabase), else 'sqlite'."""
    return "postgres" if os.getenv("DATABASE_URL") else "sqlite"


def _split_literals(sql: str):
    """Yield (chunk, is_literal) splitting on single-quoted literals.

    Handles '' escapes. Double-quoted identifiers stay code (translated).
    """
    i, n, buf = 0, len(sql), []
    while i < n:
        c = sql[i]
        if c == "'":
            if buf:
                yield "".join(buf), False
                buf = []
            j = i + 1
            lit = ["'"]
            while j < n:
                if sql[j] == "'" and j + 1 < n and sql[j + 1] == "'":
                    lit.append("''")
                    j += 2
                elif sql[j] == "'":
                    lit.append("'")
                    j += 1
                    break
                else:
                    lit.append(sql[j])
                    j += 1
            yield "".join(lit), True
            i = j
        else:
            buf.append(c)
            i += 1
    if buf:
        yield "".join(buf), False


def translate_sql(sql: str) -> str:
    """Translate one sqlite-dialect statement to Postgres. Pure function."""
    # datetime('now') straddles the literal/code boundary ('now' is quoted),
    # so match it on the raw text first — the pattern is unambiguous.
    sql = re.sub(r"(?i)\bdatetime\s*\(\s*'now'\s*\)", "CURRENT_TIMESTAMP", sql)
    out: list[str] = []
    for chunk, is_literal in _split_literals(sql):
        if is_literal:
            out.append(chunk)
            continue
        chunk = chunk.replace("?", "%s")
        chunk = re.sub(r"\[([^\]]+)\]", r'"\1"', chunk)
        chunk = re.sub(
            r"(?i)\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b",
            "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            chunk,
        )
        out.append(chunk)
    return "".join(out)


class CompatRow(tuple):
    """Tuple row with sqlite3.Row-style access: row[0], row['col'], dict(row)."""

    def __new__(cls, values: Sequence[Any], keys: Sequence[str]):
        self = super().__new__(cls, tuple(values))
        self._keys = tuple(keys)
        return self

    def __getitem__(self, k: Any) -> Any:  # type: ignore[override]
        if isinstance(k, str):
            return tuple.__getitem__(self, self._keys.index(k))
        return tuple.__getitem__(self, k)

    def keys(self) -> tuple:
        return self._keys


class _CompatCursor:
    """Wraps a psycopg cursor; translates SQL, returns CompatRow rows."""

    def __init__(self, cur: Any):
        self._cur = cur

    @property
    def description(self) -> Any:
        return self._cur.description

    def execute(self, sql: str, params: Sequence[Any] = ()) -> "_CompatCursor":
        self._cur.execute(translate_sql(sql), params)
        return self

    def executemany(self, sql: str, seq: Sequence[Sequence[Any]]) -> None:
        self._cur.executemany(translate_sql(sql), seq)

    def _wrap(self, row: Any) -> Any:
        if row is None or isinstance(row, CompatRow):
            return row
        keys = [d[0] for d in self._cur.description]
        return CompatRow(row, keys)

    def fetchone(self) -> Any:
        return self._wrap(self._cur.fetchone())

    def fetchall(self) -> list:
        return [self._wrap(r) for r in self._cur.fetchall()]

    def __iter__(self):
        for r in self._cur:
            yield self._wrap(r)


class _CompatConnection:
    """psycopg connection exposing the sqlite3-style surface main.py uses."""

    def __init__(self, conn: Any):
        self._conn = conn

    def execute(self, sql: str, params: Sequence[Any] = ()) -> _CompatCursor:
        return _CompatCursor(self._conn.cursor()).execute(sql, params)

    def executemany(self, sql: str, seq: Sequence[Sequence[Any]]) -> None:
        _CompatCursor(self._conn.cursor()).executemany(sql, seq)

    def commit(self) -> None:
        self._conn.commit()

    def rollback(self) -> None:
        self._conn.rollback()

    def close(self) -> None:
        self._conn.close()

    def __enter__(self) -> "_CompatConnection":
        return self

    def __exit__(self, *exc: Any) -> None:
        self.close()


def get_connection() -> Any:
    """Per-request connection: Supabase Postgres when DATABASE_URL is set,
    otherwise the local SQLite file (dev + tests)."""
    url = os.getenv("DATABASE_URL")
    if url:
        import psycopg  # lazy: sqlite path/tests never need the driver

        conn = psycopg.connect(url)
        return _CompatConnection(conn)
    conn = sqlite3.connect(str(DB_PATH), check_same_thread=False)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA synchronous=NORMAL")
    conn.execute("PRAGMA cache_size = -64000")
    return conn
