"""One-time loader: local SQLite -> Supabase Postgres.

Run (from backend/ directory, after `python -m app.ingest` built
data/marginmap.db)::

    $env:DATABASE_URL = "postgresql://postgres.<ref>:<pwd>@aws-0-<region>.pooler.supabase.com:6543/postgres?sslmode=require"
    python -m app.load_supabase

What it does:
  1. Rebuilds `order_margins` in Postgres from the SQLite schema
     (PRAGMA table_info -> TEXT / DOUBLE PRECISION / BIGINT, same column
     names/order) and bulk-copies all ~51k rows.
  2. Creates `flags` (IF NOT EXISTS, Postgres identity PK) and copies any
     local flag rows without clobbering existing ones, then fixes the id
     sequence.
  3. Recreates the four ingest indexes.
  4. Verifies: row counts and SUM(net_margin) / SUM(sales_effective) match
     SQLite within tolerance, else exits nonzero.

Re-running is safe: order_margins is rebuilt fresh; flags are merged.
"""
from __future__ import annotations

import os
import sqlite3
import sys

from app.database import DB_PATH

BATCH = 2000

SQLITE_TO_PG = {
    "TEXT": "TEXT",
    "REAL": "DOUBLE PRECISION",
    "INTEGER": "BIGINT",
    "NUMERIC": "NUMERIC",
    "BLOB": "BYTEA",
}

INDEXES = [
    "CREATE INDEX IF NOT EXISTS idx_margins_segment ON order_margins(Segment)",
    "CREATE INDEX IF NOT EXISTS idx_margins_category ON order_margins(Category)",
    "CREATE INDEX IF NOT EXISTS idx_margins_region ON order_margins(Region)",
    'CREATE INDEX IF NOT EXISTS idx_margins_order ON order_margins("Order ID")',
]

FLAGS_DDL_PG = """CREATE TABLE IF NOT EXISTS flags (
       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       entity_type TEXT NOT NULL,
       entity_id TEXT NOT NULL,
       status TEXT NOT NULL DEFAULT 'open',
       note TEXT NOT NULL DEFAULT '',
       flagged_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
   )"""


def qident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def main() -> int:
    url = os.getenv("DATABASE_URL")
    if not url:
        print("DATABASE_URL is not set. Set it to your Supabase Session Pooler URL first.")
        print("Dashboard -> Settings -> Database -> Connection string -> Session Pooler,")
        print("insert your database password (URL-encode special characters), add ?sslmode=require.")
        return 2
    if not DB_PATH.exists():
        print(f"Source {DB_PATH} missing. Run `python -m app.ingest` from backend/ first.")
        return 2

    try:
        import psycopg
    except ImportError:
        print("psycopg is not installed. Run `pip install -r requirements.txt` first.")
        return 2

    src = sqlite3.connect(str(DB_PATH))
    cols = src.execute("PRAGMA table_info(order_margins)").fetchall()
    if not cols:
        print("Source has no order_margins table. Run ingest first.")
        return 2
    col_names = [c[1] for c in cols]
    col_types = [SQLITE_TO_PG.get((c[2] or "TEXT").upper(), "TEXT") for c in cols]
    n_src = src.execute("SELECT COUNT(*) FROM order_margins").fetchone()[0]
    net_src = src.execute("SELECT SUM(net_margin) FROM order_margins").fetchone()[0] or 0.0
    sales_src = src.execute("SELECT SUM(sales_effective) FROM order_margins").fetchone()[0] or 0.0
    flags_src = []
    has_flags = src.execute(
        "SELECT COUNT(*) FROM sqlite_master WHERE name='flags'"
    ).fetchone()[0]
    if has_flags:
        flags_src = src.execute(
            "SELECT id, entity_type, entity_id, status, note, flagged_at FROM flags"
        ).fetchall()
    print(f"source: {n_src} order_margins rows, {len(flags_src)} flags, net {net_src:,.0f}")

    ddl = (
        "DROP TABLE IF EXISTS order_margins; "
        f"CREATE TABLE order_margins ({', '.join(f'{qident(n)} {t}' for n, t in zip(col_names, col_types))})"
    )
    placeholders = ", ".join(["%s"] * len(col_names))
    insert = (
        f"INSERT INTO order_margins ({', '.join(qident(n) for n in col_names)}) "
        f"VALUES ({placeholders})"
    )

    dst = psycopg.connect(url)
    cur = dst.cursor()
    print("creating order_margins in Supabase ...")
    cur.execute(ddl)
    print("copying rows ...")
    done = 0
    offset = 0
    while True:
        rows = src.execute(
            f"SELECT * FROM order_margins LIMIT {BATCH} OFFSET {offset}"
        ).fetchall()
        if not rows:
            break
        cur.executemany(insert, rows)
        offset += len(rows)
        done += len(rows)
        if done % 10000 == 0 or done == n_src:
            print(f"  {done}/{n_src}")
    for stmt in INDEXES:
        cur.execute(stmt)
    print("loading flags (merge, never drop) ...")
    cur.execute(FLAGS_DDL_PG)
    if flags_src:
        cur.executemany(
            "INSERT INTO flags (id, entity_type, entity_id, status, note, flagged_at) "
            "VALUES (%s, %s, %s, %s, %s, %s) ON CONFLICT (id) DO NOTHING",
            flags_src,
        )
    cur.execute(
        "SELECT setval(pg_get_serial_sequence('flags','id'), COALESCE((SELECT MAX(id) FROM flags), 1))"
    )
    dst.commit()

    n_dst = cur.execute("SELECT COUNT(*) FROM order_margins").fetchone()[0]
    net_dst = cur.execute("SELECT SUM(net_margin) FROM order_margins").fetchone()[0] or 0.0
    sales_dst = cur.execute("SELECT SUM(sales_effective) FROM order_margins").fetchone()[0] or 0.0
    print(f"dest:   {n_dst} order_margins rows, net {net_dst:,.0f}")

    ok = (
        n_dst == n_src
        and abs(net_dst - net_src) < 0.01
        and abs(sales_dst - sales_src) < 0.01
    )
    print(f"sales_effective src={sales_src:,.0f} dst={sales_dst:,.0f}")
    print("VERIFY " + ("PASS" if ok else "FAIL"))
    src.close()
    dst.close()
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
